### ISSUE TITLE
Peak to Peak value

### ISSUE THREAD

**Issue by jmatsushita** [opendroplet/opendroplet-avr#2]
From @UCLTeam

> Now, we see inputs and on the three inputs nodes, the value of node 1 is 42 which we thought is the the uid of the sensor (because in the code and the serial output we saw the value of 42 correspond to uid). The value of node 2 is changing and we think this value correspond to the peaktopeak in the serial output. And the third node is 0. We are wondering what the value of node 2 represents? What is the unit of the value?

**Comment by jmatsushita** [comment]
Correct, the value of node 1 is the uid. We don't use this currently, but we will in the future.
Node 2 is the peak to peak value, i.e. the maximum difference in amplitude on the sound wave received in the microphone for a period of 50ms. This is therefore more or less proportional to the sound pressure level (i.e. SPL). However factors such as variations in sampling rate, and the lack of calibration mean that it is not a precise measure. Remember the point we mentioned during our call [about the testing environment and current state of the detection algorithm](https://droplet.hackpad.com/Skype-Agenda-5-March-2015-l4DwalGQQsx#:h=Testing-Environment)
Node 3 is empty now, and is meant to hold the battery charge.

@aShure Anything to add?

**Comment by shulter** [comment]
Alright! The battery SOC (State Of Charge) is not implemented in hardware, the Moteino does not have such feature, a custom PCB would have that feature.
